name: Hello World Workflow

on:
    push:
        branches: [main]

jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello, world!"

            - name: Where I am
              run: pwd

            - name: create folder
              run: mkdir -p path/to/artifact

            - name: create file
              run: echo "Hello, world! My name is Carlos" > path/to/artifact/world.txt
            
            - uses: actions/upload-artifact@v4
              with:
                  name: myworld
                  path: path/to/artifact/world.txt

            - name: open file
              run: cat path/to/artifact/world.txt
